### ISSUE TITLE
NoMethodError when job_result response is broken

### ISSUE THREAD

**Issue by nahi** [treasure-data/td-client-ruby#99]
We got the following error. It is a temporary failure and usually works without any problem.
```
    NoMethodError:
      undefined method `header' for nil:NilClass
    # ./vendor/bundle/ruby/2.2.0/gems/td-client-0.8.82/lib/td/client/api/job.rb:252:in `validate_content_length_with_range'
    # ./vendor/bundle/ruby/2.2.0/gems/td-client-0.8.82/lib/td/client/api/job.rb:330:in `job_result_download'
    # ./vendor/bundle/ruby/2.2.0/gems/td-client-0.8.82/lib/td/client/api/job.rb:120:in `job_result'
    # ./vendor/bundle/ruby/2.2.0/gems/td-client-0.8.82/lib/td/client.rb:211:in `job_result'
    # ./helpers/query_api_helper.rb:93:in `to_a'
```
https://github.com/treasure-data/td-client-ruby/blob/v0.8.82/lib/td/client/api/job.rb#L294-L330
the block was not invoked and `resopnse = nil`?

**Comment by nurse** [comment]
Though it seems not the cause of this, I confirmed that redirect loop can reproduce this.

**Comment by nurse** [comment]
#109 should fix this.
